### ISSUE TITLE
`Choose options` card

### ISSUE THREAD

**Issue by vvscode** [memory-cards/rfcs#3]
Propose cards with `choose options` type. It should provide some description text and number of options. Some of them should be chosen for the correct answer, others - not.

On rendering card:
1. Shuffle all options to change an order for each interaction
1. Show button which allows checking if the current set is correct

Example:

```
> What is js-framework?
- [x] express
- [x] angular
- [ ] mimimishka
- [ ] Symphony
```

Should give a card with 4 checkboxes and a single button to check.
<img width="234" alt="screen shot 2018-10-28 at 23 03 14" src="https://user-images.githubusercontent.com/6904368/47620637-b1da6700-db05-11e8-82e6-0d5ba4d7e9bf.png">

**Comment by Space647** [comment]
Good idea, maybe we can add testing system use this cards?

**Comment by zenby** [comment]
I was thinking about it and also can propose to create two lists of questions (wrong and correct) where we with params `maxCardOptions` and `maxCorrectOptions` can randomly combine the content of test card for user.

**Comment by vvscode** [comment]
Possible implementation -

[output.apkg.zip](https://github.com/memory-cards/rfcs/files/2547269/output.apkg.zip)
